/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package application;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import utils.ImportUtils;
import year2023.day01.Day01;
import year2023.day02.Day02;

public class Application {

    private static final Map<Integer, Day> DAYS;

    static {
        DAYS = new HashMap<>();
        DAYS.put(1, new Day01());
        DAYS.put(2, new Day02());
    }

    private static List<String> loadInput(final int day) {
        String paddedDay = String.valueOf(day);
        if (day < 10) {
            paddedDay = "0" + day;
        }
        final String filePath = "src/main/resources/year2023/day" + paddedDay + "/input.txt";

        return ImportUtils.readAsList(filePath);
    }

    public static void main(final String[] args) {
        int day = 1;
        if (args.length != 0) {
            day = Integer.parseInt(args[0]);
        }

        //        int part = 1;
        //        if (args.length > 1) {
        //            part = Integer.parseInt(args[1]);
        //        }

        final List<String> input = loadInput(day);

        //        final String result;
        //        if (part == 1) {
        //            result = DAYS.get(day).part1(input);
        //        } else {
        //            result = DAYS.get(day).part2(input);
        //        }
        //
        System.out.println("Solution Part 1: " + DAYS.get(day).part1(input));
        System.out.println("Solution Part 2: " + DAYS.get(day).part2(input));

    }
}
